config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'newsletter/subscribe'
  root to: 'home#index'

  resources :posts, only: %i[index show]

  resources :about, only: %i[index]

  get 'contact', to: 'contact#index', as: 'contact'
  post 'contact', to: 'contact#create', as: 'contact_create'

  namespace :admin do
    devise_for :admin_users, path: 'auth', controllers: {
      sessions: 'admin_users/sessions'
    }

    root to: 'posts#index'

    resources :posts
    resources :categories
    resources :admin_users
    resources :newsletters
    resources :contacts
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_rich_text :body
  has_one_attached :cover

  has_and_belongs_to_many :categories

  enum state: %i[draft published]

  validates :title, :description, :state, presence: true
  validates :description, length: { maximum: 280 }
  validates :title, length: { maximum: 140 }

  # before_create :expire_caches_on_create, if: proc { Rails.env == 'production' }
  # after_update :expire_caches_on_update, if: proc { Rails.env == 'production' }

  private

  def expire_caches_on_create
    CacheService.expire_all

    Rails.cache.delete('last_5_posts_ids')
  end

  def expire_caches_on_update
    if last_5_ids.include? id
      CacheService.expire_all
    else
      CacheService.expire(cache_module: :posts)
    end
  end

  def last_5_ids
    Rails.cache.fetch('last_5_posts_ids') do
      Post.last(5).pluck(:id)
    end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    category_filter = { name: params[:category] }
    category_filter = { id: @categories } if category_filter[:name].nil?

    @posts = Post.with_attached_cover.published.includes(:categories).where(categories: category_filter)
  end

  def show
    @post = Post.published.find(params[:id])
    @post.update(count_of_views: @post.count_of_views + 1)
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_url
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_category.erb
<div class="category">
  <%= link_to category.name, posts_path(category: category.name) %>
</div>

app/views/posts/_post.erb
<article class="post-card">
  <%= image_tag post.cover.blob, class: "post-card-cover" %>
  <a href="posts/<%= post.id %>">
    <section class="post-card-body">
      <h3 class="post-card-body-title capitalize"><%= post.title %></h3>
      <h4 class="post-card-body-description"><%= post.description %></h4>
    </section>
  </a>
</article>

app/views/posts/index.html.erb
<section class="category-list-post-index">
  <% @categories.each do |category| %>
    <%= render 'category', category: category %>
  <% end %>
</section>
<section class="post-list">
  <% @posts.each do |post| %>
      <%# <%= link_to post_path(post), class: "post-link-container" do %>
      <%= render 'post', post: post %>
      <%# <% end %>
  <% end %>
</section>

app/views/posts/show.html.erb
<section class="category-list-post-show">
  <% @post.categories.each do |category| %>
    <%= render 'category', category: category %>
  <% end %>
</section>
<div class="post-body-container">
  <div class="post-body">
    <h1><%= @post.title.capitalize %></h1>
    <%= @post.body %>
  </div>
</div>