config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'newsletter/subscribe'
  root to: 'home#index'

  resources :posts, only: %i[index show]

  resources :about, only: %i[index]

  get 'contact', to: 'contact#index', as: 'contact'
  post 'contact', to: 'contact#create', as: 'contact_create'

  namespace :admin do
    devise_for :admin_users, path: 'auth', controllers: {
      sessions: 'admin_users/sessions'
    }

    root to: 'posts#index'

    resources :posts
    resources :categories
    resources :admin_users
    resources :newsletters
    resources :contacts
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :message, presence: true
  validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true }
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Contact.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Contact.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    contact = Contact.new(contact_params)

    if contact.save
      flash[:success] = 'Gracias por tu mensaje! En breves nos pondremos en contacto.'
    else
      flash[:error] = 'Ups tuvimos un problema guardando tu mensaje, por favor interna mas tarde.'
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/index.erb
<% flash.each do |key, value| %>
  <% if key.present? %>
    <div class="flex justify-center mt-16">
      <% if  key == "success" %>
        <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative w-8/12" role="alert">
          <span class="block sm:inline"><%= "#{value}"%></span>
        </div>
      <% elsif key == "error" %>
        <div class="bg-red-100 border border-Red-400 text-red-700 px-4 py-3 rounded relative w-8/12" role="alert">
          <span class="block sm:inline"><%= "#{value}"%></span>
        </div>
      <% end %>
    </div>
  <%end %>
<% end %>
<%= form_for @contact, url: contact_create_path, html: { method: :post, class: 'w-full flex justify-center mt-16'} do |f| %>
  <div class="w-8/12">
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3">
        <%= f.label :name, 'Nombre', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"%>
        <%= f.text_field :name, autocomplete: "name", class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      </div>
      <div class="w-full md:w-1/2 px-3">
        <%= f.label :email, 'Email', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"%>
        <%= f.email_field :email, autocomplete: "email" , class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3">
        <%= f.label :message, 'Mensaje', class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"%>
        <%= f.text_area :message , class: "appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" %>
      </div>
    </div>
    <%= f.submit 'Enviar', class: 'bg-gray-900 hover:bg-blue-700 text-white font-bold py-2 px-4' %>
  </div>
<% end %>