config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'newsletter/subscribe'
  root to: 'home#index'

  resources :posts, only: %i[index show]

  resources :about, only: %i[index]

  get 'contact', to: 'contact#index', as: 'contact'
  post 'contact', to: 'contact#create', as: 'contact_create'

  namespace :admin do
    devise_for :admin_users, path: 'auth', controllers: {
      sessions: 'admin_users/sessions'
    }

    root to: 'posts#index'

    resources :posts
    resources :categories
    resources :admin_users
    resources :newsletters
    resources :contacts
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise  :database_authenticatable,
          :rememberable,
          :validatable

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_and_belongs_to_many :posts

  validates :name, presence: true
  validates :name, length: { maximum: 50 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :message, presence: true
  validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true }
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true}
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_rich_text :body
  has_one_attached :cover

  has_and_belongs_to_many :categories

  enum state: %i[draft published]

  validates :title, :description, :state, presence: true
  validates :description, length: { maximum: 280 }
  validates :title, length: { maximum: 140 }

  # before_create :expire_caches_on_create, if: proc { Rails.env == 'production' }
  # after_update :expire_caches_on_update, if: proc { Rails.env == 'production' }

  private

  def expire_caches_on_create
    CacheService.expire_all

    Rails.cache.delete('last_5_posts_ids')
  end

  def expire_caches_on_update
    if last_5_ids.include? id
      CacheService.expire_all
    else
      CacheService.expire(cache_module: :posts)
    end
  end

  def last_5_ids
    Rails.cache.fetch('last_5_posts_ids') do
      Post.last(5).pluck(:id)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Contact.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Contact.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def create
    contact = Contact.new(contact_params)

    if contact.save
      flash[:success] = 'Gracias por tu mensaje! En breves nos pondremos en contacto.'
    else
      flash[:error] = 'Ups tuvimos un problema guardando tu mensaje, por favor interna mas tarde.'
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.published.order(id: :desc)
  end
end

app/controllers/newsletter_controller.rb
class NewsletterController < ApplicationController
  skip_before_action :verify_authenticity_token

  def subscribe
    Newsletter.create!(subscribe_params)

    head :ok
  rescue StandardError
    head :internal_server_error
  end

  private

  def subscribe_params
    params.permit(:email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @categories = Category.all
    category_filter = { name: params[:category] }
    category_filter = { id: @categories } if category_filter[:name].nil?

    @posts = Post.with_attached_cover.published.includes(:categories).where(categories: category_filter)
  end

  def show
    @post = Post.published.find(params[:id])
    @post.update(count_of_views: @post.count_of_views + 1)
  rescue ActiveRecord::RecordNotFound
    redirect_to posts_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/fields/rich_text_area_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.rich_text_area field.attribute %>
</div>

app/views/fields/rich_text_area_field/_index.html.erb
<%# <%= field.to_s %> %>
<%= 'hola' %>

app/views/fields/rich_text_area_field/_show.html.erb
<%= field.to_s %>

app/views/layouts/_about_me_header.erb
<header class="flex justify-center">
  <%= image_tag asset_path("logo.png"), class: 'w-64 h-64' %>
</header>

app/views/layouts/_blog_header.erb
<div class="blog-header">
  <%= image_tag asset_path("logo_handwrite.png") %>
</div>

app/views/layouts/_home_header.erb
<div class="home-header">
  <a href="/">
    <%= image_tag asset_path("logo_handwrite.png") %>
  </a>
</div>

app/views/layouts/_nav_bar.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Inicio', root_path %>
    </li>
    <li>
      <%= link_to 'Blog', posts_path %>
    </li>
    <li>
      <%= link_to 'Sobre', about_index_path %>
    </li>
    <li>
      <%= link_to 'Contacto', contact_path %>
    </li>
  </ul>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="robots" content="noodp, noydir, index, follow">
    <meta name="viewport" content="initial-scale=1">
    <title>
      <%= content_for(:title) || 'Dashboard' %> - <%= Rails.application.class.parent_name.titlecase %>
    </title>
    <%= javascript_pack_tag 'administrate', 'data-turbolinks-track': 'reload' %>

    <%= render "stylesheet" %>
    <%= csrf_meta_tags %>


    <meta name="turbolinks-root" content="/admin">
  </head>
  <body>
    <div class="app-container">
      <%= render "navigation" -%>

      <main class="main-content" role="main">
        <%= render "flashes" -%>
        <%= yield %>
      </main>
    </div>

    <div style="display: none; width: 0; height: 0; overflow: hidden; position: absolute">
      <%= render "icons" %>
    </div>
    <%= render "javascript" %>
  </body>
</html>

app/views/layouts/admin/sign_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>EuphoriaDesign | Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body-container">
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>EuphoriaDesign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700|Syncopate&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-149113590-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-149113590-1');
      </script>
  <% end %>
  </head>

  <body>
    <%=  render 'layouts/nav_bar' %>
    <% if controller.class == HomeController %>
      <%= render 'layouts/home_header' %>
    <% elsif controller.class ==  PostsController %>
      <%= render 'layouts/blog_header' %>
    <%end%>
    <%= yield %>
    <footer class="footer">
      <h2>EUPHORIA DESIGN</h2>
      <div class="footer-main">
        <div class="footer-section">
          <ul class="footer-social-networks">
            <li class="mr-16">
              <%= link_to Rails.application.config.social_networks_urls[:facebook] do %>
                <%= fa_icon "facebook" %>
              <% end %>
            </li>
            <li>
              <%= link_to Rails.application.config.social_networks_urls[:instagram] do %>
                <%= fa_icon "instagram" %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="footer-section footer-section-border flex-col" data-controller="subscribe">
          <input data-target="subscribe.email" type="text" name="email" placeholder="Email" class="border border-gray-200 py-2 px-4 block w-full appearance-none leading-normal mb-4" style="background-color: #000000">
          <input data-action="click->subscribe#send" type="submit" value="Subscribirse ahora" class="border border-gray-200 py-2 px-4 block w-full appearance-none leading-normal" style="background-color: #000000">
        </div>
        <div class="footer-section">
          <p><span><%= fa_icon "copyright" %></span> 2019 Euphoria Design by Nati Silveira</p>
        </div>
      </div>
    </footer>
  </body>
</html>